#
#
- hosts: master
  become: yes

  tasks:
  - name: Swap off
    become: yes
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: Delete .kube if it exists
    become: yes
    file:
      state: absent
      path: /home/pi/.kube


  - name: run kubeadm reset -f
    become: yes
    command: kubeadm reset -f
    args:
      removes: /etc/kubernetes/admin.conf

  - name: Initialize the Kubernetes cluster using kubeadm
    become: yes
    command: kubeadm init --apiserver-advertise-address="10.0.0.50" --apiserver-cert-extra-sans="10.0.0.50"  --pod-network-cidr=10.244.0.
0/16


  - name: create .kube directory
    file:
      path: /home/pi/.kube
      state: directory
      mode: 0755 

  - name: copies admin.conf to user's kube config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/pi/.kube/config
      remote_src: yes
      owner: pi

  - name: Install flannel pod network
    become: yes
    become_user: pi
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

  - name: Generate join command
    become: yes
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Copy join command to local file
    become: yes
    local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"
